apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
data:
  xpack.security.enrollment.enabled: "false"
  discovery.type: "single-node"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  indices.memory.index_buffer_size: "10%"
  indices.memory.min_index_buffer_size: "48mb"
